<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>GR Lens Distribuidora</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet"/>
<style>
  :root{
    --bg:#f6f7f8;
    --panel:#ffffff;
    --ink:#111318;
    --ink-soft:#5e646b;
    --line:#e5e7eb;
    --brand:#0ea5e9;        /* celeste sutil */
    --brand-ink:#ffffff;
    --accent:#1f2937;       /* gris oscuro */
    --ok:#22c55e;
    --shadow:0 8px 30px rgba(0,0,0,.06);
    --radius:14px;
  }
  *{box-sizing:border-box}
  body{
    margin:0; background:var(--bg); color:var(--ink);
    font-family:'Inter',system-ui,-apple-system,Segoe UI,Roboto,Arial;
  }

  /* HEADER */
  header{
    position:sticky; top:0; z-index:40;
    background:var(--panel); box-shadow:var(--shadow);
    display:flex; align-items:center; justify-content:space-between;
    gap:20px; padding:12px 22px; border-bottom:1px solid var(--line);
  }
  .hdr-left{display:flex; align-items:center; gap:12px}
  .logo{height:36px; width:auto}
  .brand-title{font-weight:700}
  nav a{
    text-decoration:none; color:var(--ink); font-weight:600; margin-left:18px;
  }
  nav a:hover{color:var(--brand)}
  .whatsapp{
    margin-left:14px; background:#25d366; color:#fff; padding:8px 12px;
    border-radius:999px; text-decoration:none; font-weight:700;
  }
  .hamburger{
    display:none; border:1px solid var(--line); background:var(--panel);
    padding:8px 10px; border-radius:10px; cursor:pointer;
  }

  /* LAYOUT */
  .layout{display:grid; grid-template-columns:260px 1fr; gap:22px; padding:18px; max-width:1400px; margin:0 auto;}
  /* SIDEBAR */
  aside{
    position:sticky; top:86px; align-self:start;
    background:var(--panel); border:1px solid var(--line); border-radius:var(--radius);
    padding:18px; box-shadow:var(--shadow);
    max-height:calc(100vh - 110px); overflow:auto;
  }
  aside h3{margin:0 0 12px 0; font-size:15px; color:var(--ink-soft); letter-spacing:.02em}
  .cat-list{display:flex; flex-direction:column; gap:6px}
  .cat-list a{
    display:block; padding:10px 12px; border-radius:10px; text-decoration:none;
    color:var(--ink); border:1px solid var(--line); background:var(--panel);
    transition:.2s;
  }
  .cat-list a:hover{border-color:var(--brand); box-shadow:0 6px 18px rgba(14,165,233,.12)}
  .cat-list a.active{background:var(--brand); color:var(--brand-ink); border-color:var(--brand)}

  /* MAIN */
  main{display:flex; flex-direction:column; gap:18px}
  .banner{
    height:280px; border-radius:var(--radius); overflow:hidden; background:#ddd;
    border:1px solid var(--line); box-shadow:var(--shadow);
  }
  .banner img{width:100%; height:100%; object-fit:cover; display:block}
  .toolbar{
    display:flex; gap:12px; align-items:center; justify-content:space-between;
    background:var(--panel); padding:14px; border:1px solid var(--line);
    border-radius:var(--radius); box-shadow:var(--shadow);
  }
  .search{
    flex:1; display:flex; align-items:center; gap:10px;
    border:1px solid var(--line); padding:10px 12px; border-radius:12px; background:#fff;
  }
  .search input{border:none; outline:none; width:100%; font-size:15px}
  .chips{display:flex; flex-wrap:wrap; gap:8px}
  .chip{
    padding:8px 10px; border-radius:20px; border:1px solid var(--line);
    background:#fff; cursor:pointer; font-size:13px;
  }
  .chip.active{background:var(--brand); color:#fff; border-color:var(--brand)}

  .grid{
    display:grid; grid-template-columns:repeat(12,1fr); gap:16px;
  }
  .col-3{grid-column:span 3}
  @media (max-width:1200px){.col-3{grid-column:span 4}}
  @media (max-width:900px){.layout{grid-template-columns:1fr} aside{display:none} .hamburger{display:inline-block} .col-3{grid-column:span 6}}
  @media (max-width:560px){.col-3{grid-column:span 12}}

  .card{
    background:var(--panel); border:1px solid var(--line); border-radius:16px; overflow:hidden;
    display:flex; flex-direction:column; box-shadow:var(--shadow); transition:transform .15s ease;
  }
  .card:hover{transform:translateY(-2px)}
  .thumb{aspect-ratio:1.3/1; background:#eef2f7}
  .thumb img{width:100%; height:100%; object-fit:cover}
  .body{padding:12px}
  .title{font-weight:700; margin:0 0 4px 0}
  .meta{color:var(--ink-soft); font-size:13px; margin-bottom:8px}
  .price{font-weight:800; margin-bottom:8px}
  .stock{font-size:12px; color:var(--ok)}
  .actions{display:flex; gap:10px; margin-top:12px}
  .btn{
    border:1px solid var(--line); background:#fff; padding:8px 10px; border-radius:10px; cursor:pointer;
    font-weight:600;
  }
  .btn.primary{background:var(--brand); color:#fff; border-color:var(--brand)}
  .btn:hover{opacity:.92}

  /* CART DRAWER */
  .cart{
    position:fixed; inset:0 0 0 auto; width:380px; max-width:92vw; background:#fff; box-shadow:-20px 0 40px rgba(0,0,0,.18);
    transform:translateX(102%); transition:transform .25s ease; z-index:50; display:flex; flex-direction:column;
  }
  .cart.open{transform:none}
  .cart-hd{display:flex; align-items:center; justify-content:space-between; padding:14px 16px; border-bottom:1px solid var(--line)}
  .cart-body{padding:14px 16px; overflow:auto; flex:1; display:flex; flex-direction:column; gap:12px}
  .cart-item{display:flex; justify-content:space-between; gap:10px; border:1px solid var(--line); border-radius:12px; padding:10px}
  .cart-ft{border-top:1px solid var(--line); padding:14px 16px}
  .sum{display:flex; justify-content:space-between; font-weight:800; margin-bottom:10px}
  .btn.full{width:100%}
  .cart-toggle{
    position:fixed; right:18px; bottom:18px; z-index:45; border:none; background:var(--accent); color:#fff;
    padding:12px 16px; border-radius:12px; box-shadow:var(--shadow); cursor:pointer; font-weight:800;
  }

  /* Toast */
  .toast{
    position:fixed; right:18px; bottom:82px; background:var(--ink); color:#fff; padding:10px 14px; border-radius:10px;
    opacity:0; transform:translateY(10px); transition:.25s; z-index:60;
  }
  .toast.show{opacity:1; transform:none}
</style>
</head>
<body>

<!-- HEADER -->
<header>
  <div class="hdr-left">
    <button class="hamburger" id="btnMenu">☰</button>
    <img class="logo" src="logotipo.png" alt="GR Lens">
    <div class="brand-title">GR Lens Distribuidora</div>
  </div>
  <nav>
    <a href="#inicio">Inicio</a>
    <a href="#categorias">Categorías</a>
    <a href="#micuenta">Mi cuenta</a>
    <a class="whatsapp" target="_blank" href="https://wa.me/TU_NUMERO_CON_CODIGO">WhatsApp</a>
  </nav>
</header>

<div class="layout">

  <!-- SIDEBAR -->
  <aside id="sidebar">
    <h3>Categorías</h3>
    <div class="cat-list" id="catList">
      <!-- Se marca active por script cuando se filtra -->
      <a data-cat="Unicity">Unicity</a>
      <a data-cat="Vicrola">Vicrola</a>
      <a data-cat="Steffany">Steffany</a>
      <a data-cat="Metal Dama">Metal Dama</a>
      <a data-cat="Metal Dama Premium">Metal Dama Premium</a>
      <a data-cat="Metal Caballero">Metal Caballero</a>
      <a data-cat="Metal Caballero Premium">Metal Caballero Premium</a>
      <a data-cat="Acetato Dama">Acetato Dama</a>
      <a data-cat="Acetato Caballero">Acetato Caballero</a>
      <a data-cat="Acetato Económico">Acetato Económico</a>
      <a data-cat="Acetato Premium">Acetato Premium</a>
      <a data-cat="TR Clip On">TR Clip On</a>
      <a data-cat="Acetato Clip On">Acetato Clip On</a>
      <a data-cat="Clip On 360° Premium">Clip On 360° Premium</a>
      <a data-cat="Nylon Dama">Nylon Dama</a>
    </div>
  </aside>

  <!-- MAIN -->
  <main>
    <section class="banner"><img src="banner.png" alt="Banner GR Lens"></section>

    <section class="toolbar">
      <div class="search">
        🔎 <input id="search" type="search" placeholder="Buscar por nombre o modelo..." />
      </div>
      <div class="chips" id="chips">
        <!-- Chips de categoría rápidas -->
      </div>
      <button class="btn" id="btnClear">Limpiar filtros</button>
    </section>

    <section class="grid" id="grid">
      <!-- Tarjetas de productos renderizadas por JS -->
    </section>
  </main>
</div>

<!-- CART TOGGLE -->
<button class="cart-toggle" id="openCart">🛒 Carrito <span id="cartCount">0</span></button>

<!-- CART DRAWER -->
<aside class="cart" id="cart">
  <div class="cart-hd">
    <strong>Carrito</strong>
    <button class="btn" id="closeCart">Cerrar</button>
  </div>
  <div class="cart-body" id="cartBody"></div>
  <div class="cart-ft">
    <div class="sum"><span>Total</span><span id="cartTotal">$ 0</span></div>
    <button class="btn primary full" id="checkout">Completar pedido</button>
    <small style="color:var(--ink-soft)">Este sitio no procesa pagos. Te contactaremos por WhatsApp para coordinar CBU y entrega.</small>
  </div>
</aside>

<div class="toast" id="toast">Agregado al carrito ✓</div>

<script>
/* ---------- Datos de ejemplo (editables) ---------- */
/* Reemplazá/extendé esta lista para cargar tus productos reales */
const PRODUCTS = [
  { id:'A1-AC',  nombre:'Armazón Clásico A1',        modelo:'A1-AC',  cat:'Acetato Dama',         precio:25000, stock:12, img:'' },
  { id:'U2-TR',  nombre:'Armazón Ultraliviano U2',   modelo:'U2-TR',  cat:'TR Clip On',           precio:31000, stock:7,  img:'' },
  { id:'M5-ME',  nombre:'Armazón Metálico M5',       modelo:'M5-ME',  cat:'Metal Caballero',      precio:29000, stock:9,  img:'' },
  { id:'P3-AC',  nombre:'Acetato Premium P3',        modelo:'P3-AC',  cat:'Acetato Premium',      precio:36000, stock:5,  img:'' },
  { id:'CL-360', nombre:'Clip On 360º Premium C1',   modelo:'CL-360', cat:'Clip On 360° Premium', precio:42000, stock:6,  img:'' },
  { id:'NY-D1',  nombre:'Nylon Dama ND1',            modelo:'NY-D1',  cat:'Nylon Dama',           precio:27000, stock:8,  img:'' },
];

/* ---------- Render UI ---------- */
const grid = document.getElementById('grid');
const search = document.getElementById('search');
const chips = document.getElementById('chips');
const catList = document.getElementById('catList');
const btnClear = document.getElementById('btnClear');
const cartBtn = document.getElementById('openCart');
const cart = document.getElementById('cart');
const closeCart = document.getElementById('closeCart');
const cartBody = document.getElementById('cartBody');
const cartTotal = document.getElementById('cartTotal');
const cartCount = document.getElementById('cartCount');
const toast = document.getElementById('toast');
const btnMenu = document.getElementById('btnMenu');
const sidebar = document.getElementById('sidebar');

let state = {
  q:'',
  cat:null
};

let CART = JSON.parse(localStorage.getItem('grlens_cart')||'[]');

function money(n){ return '$ ' + n.toLocaleString('es-AR'); }

function renderChips(){
  const cats = [...new Set(PRODUCTS.map(p=>p.cat))];
  chips.innerHTML = cats.map(c => `<button class="chip" data-chip="${c}">${c}</button>`).join('');
  chips.addEventListener('click', e=>{
    const c = e.target.closest('.chip'); if(!c) return;
    document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));
    c.classList.add('active');
    state.cat = c.dataset.chip;
    highlightSidebar(c.dataset.chip);
    renderProducts();
  });
}
function highlightSidebar(cat){
  document.querySelectorAll('.cat-list a').forEach(a=>{
    a.classList.toggle('active', a.dataset.cat===cat);
  });
}
function renderProducts(){
  let list = PRODUCTS.filter(p=>{
    const okCat = !state.cat || p.cat===state.cat;
    const okQ = !state.q || (p.nombre+p.modelo).toLowerCase().includes(state.q.toLowerCase());
    return okCat && okQ;
  });
  grid.innerHTML = list.map(p=>`
    <article class="card col-3">
      <div class="thumb">${p.img? `<img src="${p.img}" alt="${p.nombre}">` : ''}</div>
      <div class="body">
        <h4 class="title">${p.nombre}</h4>
        <div class="meta">${p.modelo} · <span style="color:var(--ink-soft)">${p.cat}</span></div>
        <div class="price">${money(p.precio)}</div>
        <div class="stock">Stock: ${p.stock}</div>
        <div class="actions">
          <button class="btn" onclick="quickView('${p.id}')">Ver</button>
          <button class="btn primary" onclick="addToCart('${p.id}')">Agregar</button>
        </div>
      </div>
    </article>
  `).join('');
}
function quickView(id){
  const p = PRODUCTS.find(x=>x.id===id);
  alert(`${p.nombre}\nModelo: ${p.modelo}\nCategoría: ${p.cat}\nPrecio: ${money(p.precio)}`);
}
function addToCart(id){
  const p = PRODUCTS.find(x=>x.id===id);
  const item = CART.find(i=>i.id===id);
  if(item){ item.qty++; } else { CART.push({id:p.id, nombre:p.nombre, precio:p.precio, qty:1}); }
  saveCart(); renderCart(); showToast('Agregado al carrito ✓');
}
function saveCart(){ localStorage.setItem('grlens_cart', JSON.stringify(CART)); }
function renderCart(){
  cartBody.innerHTML = CART.length ? CART.map(i=>`
    <div class="cart-item">
      <div>
        <strong>${i.nombre}</strong><br>
        <small>${money(i.precio)} x ${i.qty}</small>
      </div>
      <div>
        <button class="btn" onclick="decQty('${i.id}')">-</button>
        <button class="btn" onclick="incQty('${i.id}')">+</button>
        <button class="btn" onclick="removeItem('${i.id}')">✕</button>
      </div>
    </div>
  `).join('') : '<small style="color:var(--ink-soft)">Todavía no agregaste productos.</small>';
  const total = CART.reduce((a,i)=>a+i.precio*i.qty,0);
  cartTotal.textContent = money(total);
  cartCount.textContent = CART.reduce((a,i)=>a+i.qty,0);
}
function decQty(id){ const it=CART.find(x=>x.id===id); if(!it) return; it.qty--; if(it.qty<=0) CART=CART.filter(x=>x.id!==id); saveCart(); renderCart(); }
function incQty(id){ const it=CART.find(x=>x.id===id); if(!it) return; it.qty++; saveCart(); renderCart(); }
function removeItem(id){ CART=CART.filter(x=>x.id!==id); saveCart(); renderCart(); }

function showToast(msg){
  toast.textContent = msg; toast.classList.add('show');
  setTimeout(()=>toast.classList.remove('show'), 1400);
}

/* Checkout -> WhatsApp */
document.getElementById('checkout').addEventListener('click', ()=>{
  if(!CART.length){ showToast('El carrito está vacío'); return; }
  const total = CART.reduce((a,i)=>a+i.precio*i.qty,0);
  const lines = CART.map(i=>`• ${i.nombre} x${i.qty} – ${money(i.precio*i.qty)}`).join('%0A');
  const text = `Hola! Quiero completar el pedido:%0A${lines}%0A%0ATotal: ${money(total)}%0A%0ACliente: (nombre y óptica)%0AZona: (tu zona)`;
  window.open(`https://wa.me/TU_NUMERO_CON_CODIGO?text=${text}`, '_blank');
});

/* Filtros */
search.addEventListener('input', e=>{ state.q = e.target.value.trim(); renderProducts(); });
btnClear.addEventListener('click', ()=>{
  state = {q:'',cat:null}; search.value='';
  document.querySelectorAll('.chip, .cat-list a').forEach(x=>x.classList.remove('active'));
  renderProducts();
});
catList.addEventListener('click', e=>{
  const a = e.target.closest('a'); if(!a) return;
  state.cat = a.dataset.cat;
  highlightSidebar(state.cat);
  document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active', x.dataset.chip===state.cat));
  renderProducts();
});

/* Sidebar toggle mobile */
btnMenu.addEventListener('click', ()=>{
  if(getComputedStyle(sidebar).display==='none'){ sidebar.style.display='block'; window.scrollTo({top:0, behavior:'smooth'}); }
  else sidebar.style.display='none';
});

/* Cart open/close */
cartBtn.addEventListener('click', ()=>cart.classList.add('open'));
closeCart.addEventListener('click', ()=>cart.classList.remove('open'));

/* Init */
renderChips();
renderProducts();
renderCart();
</script>
</body>
</html>
